### ISSUE TITLE
Image files not showing

### ISSUE THREAD

**Issue by onurerikci** [J-CITY/tinyWinToast#3]
I tried this code but image files not showing:

logo = os.path.join(root, "./visuals/logo/logo.ico")
toast = Toast()
toast.setTitle("TITLE", maxLines=1)
toast.setMessage("MESSAGE", maxLines=1)
toast.addText("from email", placement="attribution", maxLines=1)
toast.setIcon(logo, crop="none")
toast.show()

icon,heroimage and image not show images

**Comment by J-CITY** [comment]
Hi! I think it because you have wrong path. You need give absolute path to image. Try hardcode image path and test it.

**Comment by onrerkc** [comment]
i test it but same result :(

**Comment by onurerikci** [comment]
ok, it works thx you for this beautiful project!
